.TH xaralx 1 "Aug 10, 2006" xaralx
.SH NAME
Xara Xtreme LX (xaralx) - a fast and flexible vector graphics program

.SH SYNOPSIS
.B xaralx
[\fIOPTIONS\fR] [\fIFilename\fR ...]

.SH DESCRIPTION
\fBXara Xtreme LX (xaralx)\fR is an open-source vector graphic program, designed for
speed, flexibility and slickness of user-interface.

.SH USAGE
\fBxaralx\fR will start the Xara Xtreme LX application.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
prints out the usage and exits
.TP
\fB\-v\fR, \fB\-\-version\fR
prints out the version and build date and exits
.TP
\fB\-r\fR, \fB\-\-resources=\fR\fIdirectory\fR
Resources contain dialogs and string tables used by Xtreme LX. 
Normally Xtreme LX uses those linked into the executable.
See \fIhttp://www.xaraxtreme.org/developers/documentation/resource_system_introduction.html\fR

.SH FILES
\fI${HOME}/.xaralx/preferences\fR - file containing options for Xara Xtreme LX

.SH BUGS
To report a bug, please visit \fIhttp://bugzilla.xaralx.org/\fR

.SH AUTHORS
.TP
.B Copyright (C) 1993-2006 Xara Group Ltd.
Certain other persons may hold copyright on certain files.
See the file LICENSE distributed with Xara Xtreme LX for licensing
details
.I http://www.xaraxtreme.org/
