.TH XARALX 1 "May 16, 2006" XaraLX
.SH NAME
XaraLX - a fast and flexible vector graphics program

.SH SYNOPSIS
.B XaraLX
[\fIOPTIONS\fR] [\fIFilename\fR ...]

.SH DESCRIPTION
\fBXaraLX\fR is an open-source vector graphic program, designed for
speed, flexibility and slickness of user-interface.

.SH USAGE
\fBXaraLX\fR will start the XaraLX application.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
prints out the usage and exits
.TP
\fB\-v\fR, \fB\-\-version\fR
prints out the version and build date and exits
.TP
\fB\-r\fR, \fB\-\-resources=\fR\fIdirectory\fR
Resources contain dialogs and string tables used by XaraLX. 
Normally XaraLX uses those linked into the executable.
See \fIhttp://www.xaraxtreme.org/developers/documentation/resource_system_introduction.html\fR

.SH FILES
\fI${HOME}/.XaraLX\fR - file containing options for XaraLX

.SH BUGS
To report a bug, please visit \fIhttp://bugzilla.xaralx.org/\fR

.SH AUTHORS
.TP
.B Copyright (C) 1993-2006 Xara Group Ltd.
Certain other persons may hold copyright on certain file.
See the file LICENSE distributed with XaraLX for licensing
details
.I http://www.xaralx.org/
