.TH XARALX 1 "May 16, 2006" XaraLX
.SH NAME
XaraLX - a fast and flexible vector graphics program

.SH SYNOPSIS
.B XaraLX
[\fIOPTIONS\fR] [\fIFilename\fR ...]

.SH DESCRIPTION
\fBXaraLX\fR is an open-source vector graphic program, designed for
speed, flexibility and slickness of user-interface.

.SH USAGE
\fBXaraLX\fR will start the XaraLX application.

.SH OPTIONS
A summary of the options supported by \fXaraLX\fR is available
at http://www.xaralx.org/

.SH FILES
\fI${HOME}/.XaraLX\fR - file containing options for XaraLX

.SH BUGS
To report a bug, please visit \fIhttp://bugzilla.xaralx.org/\fR

.SH AUTHORS
.TP
.B Copyright (C) 1993-2006 Xara Group Ltd.
Certain other persons may hold copyright on certain file.
See the file LICENSE distributed with XaraLX for licensing
details
.I http://www.xaralx.org/
