HotKey	"WXK_TAB"		Constrain				"Ctrl+Tab"		"NextDocument"
HotKey	"WXK_TAB"		Adjust Constrain		"Ctrl+Shift+Tab" "LastDocument"

HotKey	"WXK_A"		Constrain				"Ctrl+A"		"SelectAll"
HotKey	"WXK_A"		Adjust Constrain		"Ctrl+Shift+A"	"PasteAttributes"
HotKey	"WXK_B"		Constrain				"Ctrl+B"		"PutToBack"
HotKey	"WXK_B"		Adjust Constrain		"Ctrl+Shift+B"	"MoveBackwards"
HotKey	"WXK_C"		Constrain				"Ctrl+C"		"Copy"
HotKey	"WXK_C" 		Adjust Constrain 		"Ctrl+Shift+C"	"ConvertToBitmap"
HotKey	"WXK_D"		Constrain				"Ctrl+D"		"Duplicate"
HotKey	"WXK_D"		Adjust Constrain		"Ctrl+Shift+D"	"MoveBackwardsALayer"
HotKey	"WXK_E"		Constrain				"Ctrl+E"		"ColourPicker"
HotKey	"WXK_E"		Adjust Constrain		"Ctrl+Shift+E"	"Export"
HotKey	"WXK_F"		Constrain				"Ctrl+F"		"BringToFront"
HotKey	"WXK_F"		Adjust Constrain		"Ctrl+Shift+F"	"MoveForwards"
HotKey	"WXK_G"		Constrain				"Ctrl+G"		"Group"
HotKey	"WXK_G"		Adjust Constrain		"Ctrl+Shift+G"	"Group"
HotKey	"WXK_W"		Constrain				"Ctrl+W"		"FileClose"
HotKey	"WXK_I"		Adjust Constrain		"Ctrl+Shift+I"	"Import"
HotKey	"WXK_I"		Constrain				"Ctrl+I"		"ImageSlice"
HotKey	"WXK_J"		Adjust Constrain		"Ctrl+Shift+J"	"ZoomDrawing"
HotKey	"WXK_K"		Constrain				"Ctrl+K"		"EditClone"
HotKey	"WXK_L"		Constrain				"Ctrl+L"		"ViewRulers"
HotKey	"WXK_L"		Adjust Constrain		"Ctrl+Shift+L"	"ArrangeAlignment"
HotKey	"WXK_N"		Constrain				"Ctrl+N"		"FileNewDrawing"
HotKey	"WXK_N"		Adjust Constrain		"Ctrl+Shift+N"	"FileNewAnimation"
HotKey	"WXK_O"		Constrain				"Ctrl+O"		"FileOpen"
HotKey	"WXK_O"		Adjust Constrain		"Ctrl+Shift+O"	"UtilOptions"
HotKey	"WXK_P"		Constrain				"Ctrl+P"		"Print"
HotKey	"WXK_P"		Adjust Constrain		"Ctrl+Shift+P"	"ZoomSpread"
HotKey  "WXK_R"		Constrain				"Ctrl+R"		"ZoomPrev"
HotKey  "WXK_R"		Adjust Constrain		"Ctrl+Shift+R"	"ReverseStoryPath"
HotKey	"WXK_S"		Constrain				"Ctrl+S"		"FileSave"
HotKey	"WXK_S"		Adjust Constrain		"Ctrl+Shift+S"	"ConvertToShapes"
HotKey  "WXK_T"		Adjust Constrain		"Ctrl+Shift+T"	"TimeDraw"
HotKey	"WXK_U"		Constrain				"Ctrl+U"		"Ungroup"
HotKey	"WXK_U"		Adjust Constrain 		"Ctrl+Shift+U"	"MoveForwardsALayer"
HotKey	"WXK_V"		Constrain				"Ctrl+V"		"Paste"
HotKey	"WXK_V"		Adjust Constrain		"Ctrl+Shift+V"	"PasteAtSamePos"
HotKey	"WXK_W"		Adjust Constrain		"Ctrl+Shift+W"	"WebAddressDlg"
HotKey	"WXK_X"		Constrain				"Ctrl+X"		"Cut"
HotKey	"WXK_Y"		Constrain				"Ctrl+Y"		"Redo"
HotKey	"WXK_Y"		Adjust Constrain		"Ctrl+Shift+Y"	"URLImport"
HotKey	"WXK_Z"		Constrain				"Ctrl+Z"		"Undo"
HotKey  "WXK_Z"		Adjust Constrain		"Ctrl+Shift+Z"	"ZoomSelect"
HotKey	"WXK_LESS"							"<"				"Undo"
HotKey	"WXK_GREATER"							">"				"Redo"
HotKey	"WXK_ESCAPE"							"Esc"			"SelectNone"
HotKey	"WXK_BACK"								"Backspace"		"Cut"
HotKey	"WXK_DELETE" 	Extended				"Del"			"Delete"
HotKey	"WXK_DELETE" 							"Del"			"Delete"
HotKey	"WXK_INSERT" 	Extended				"Ins"			"Paste"
HotKey	"WXK_HASH"		CheckUnicode			"#"				"ShowGrid"
HotKey	"WXK_RETURN"							"Return"		"EditSelection"
HotKey	"WXK_RETURN"	Extended				"Enter"			"EditSelection"
HotKey	"WXK_INSERT"	Extended Adjust			"Shift+Insert"	"Paste"
HotKey	"WXK_INSERT"	Extended Constrain		"Ctrl+Insert"	"Copy"
HotKey	"WXK_DELETE"	Adjust					"Shift+Delete"	"Cut"
HotKey	"WXK_DELETE"	Extended Adjust			"Shift+Delete"	"Cut"
HotKey	"WXK_NUMPAD8"							"NumPad 8"		"ViewFullScreen"
HotKey	"WXK_F1"	Extended				"F1"			"HelpIndex"
HotKey	"WXK_NUMPAD_MULTIPLY"	WorksInDrag				"NumPad *"		"SnapToObjects"
HotKey	"WXK_NUMPAD_DECIMAL"	WorksInDrag Extended	"NumPad ."		"SnapToGrid"
HotKey	"WXK_NUMPAD2"	WorksInDrag				"NumPad 2"		"SnapToGuides"
HotKey	"WXK_NUMPAD1"  						"NumPad 1"		"ShowGuides"
HotKey	"WXK_1"	Constrain			"Ctrl+1"			"AddShapes"
HotKey	"WXK_2"	Constrain			"Ctrl+2"			"SubtractShapes"
HotKey  "WXK_3"	Constrain			"Ctrl+3"			"IntersectShapes"
HotKey  "WXK_4"	Constrain			"Ctrl+4"			"SliceShapes"
HotKey  "WXK_8"	Adjust Constrain		"Ctrl+Shift+8"			"CXFTreeDlg"
HotKey  "WXK_9"	Adjust Constrain		"Ctrl+Shift+9"			"ThrottleCache"
HotKey  "WXK_0"	Adjust Constrain		"Ctrl+Shift+0"			"ClearCache"
HotKey  "WXK_NUMPAD_ADD"	Constrain		"Ctrl+NumPad +"		"ZoomIn"
HotKey  "WXK_NUMPAD_SUBTRACT"	Constrain		"Ctrl+NumPad -"		"ZoomOut"
HotKey	"WXK_1"		Alternative		"Alt+1"				"TOOL13"
HotKey	"WXK_2"		Alternative		"Alt+2"				"TOOL17"
HotKey  "WXK_3"		Alternative		"Alt+3"				"TOOL22"
HotKey  "WXK_4"		Alternative		"Alt+4"				"TOOL23"
HotKey  "WXK_5"		Alternative		"Alt+5"				"TOOL24"
HotKey  "WXK_6"		Alternative		"Alt+6"				"TOOL16"
HotKey  "WXK_7"		Alternative		"Alt+7"				"TOOL19"
HotKey  "WXK_8"		Alternative		"Alt+8"				"TOOL25"
HotKey  "WXK_9"		Alternative		"Alt+9"				"TOOL3"
HotKey  "WXK_0"		Alternative		"Alt+0"				"TOOL4"
HotKey  "WXK_F2"	Extended			"F2"				"TOOL7"
HotKey  "WXK_F3"	Extended			"F3"				"TOOL6"
HotKey  "WXK_F4"	Extended			"F4"				"TOOL11"
HotKey  "WXK_F5"	Extended			"F5"				"TOOL13"
HotKey	"WXK_F6"	Extended			"F6"				"TOOL17"
HotKey	"WXK_F7"	Extended			"F7"				"TOOL16"
HotKey	"WXK_F8"	Extended			"F8"				"TOOL21"
HotKey	"WXK_F2"	Adjust Extended		"Shift+F2"			"TOOL18"
HotKey	"WXK_F3"	Adjust Extended		"Shift+F3"			"TOOL5"
HotKey	"WXK_F4"	Adjust Extended		"Shift+F4"			"TOOL12"
HotKey	"WXK_F5"	Adjust Extended		"Shift+F5"			"TOOL14"
HotKey	"WXK_F6"	Adjust Extended		"Shift+F6"			"TOOL19"
HotKey	"WXK_F7"	Adjust Extended		"Shift+F7"			"TOOL4"
HotKey	"WXK_F8"	Adjust Extended		"Shift+F8"			"TOOL3"
HotKey	"WXK_F2"	Constrain Extended	"Ctrl+F2"			"TOOL22"
HotKey  "WXK_F3"	Constrain Extended	"Ctrl+F3"			"TOOL23"
HotKey  "WXK_F5"	Constrain Extended	"Ctrl+F5"			"TOOL26"
HotKey	"WXK_F7"	Constrain Extended	"Ctrl+F7"			"TOOL24"
HotKey	"WXK_F8"	Constrain Extended	"Ctrl+F8"			"TOOL25"
HotKey	"WXK_F9"	Extended			"F9"				"DisplayColourGallery"
HotKey	"WXK_F10"	Extended			"F10"				"DisplayLayerGallery"
HotKey	"WXK_F11"	Extended			"F11"				"DisplayBitmapGallery"
HotKey	"WXK_F12"	Extended			"F12"				"DisplayLineGallery"
HotKey	"WXK_F9"	Adjust Extended		"Shift+F9"			"DisplayFontsGallery"
HotKey	"WXK_F10"	Adjust Extended		"Shift+F10"			"DisplayClipartGallery"
HotKey	"WXK_F11"	Adjust Extended		"Shift+F11"			"DisplayFillsGallery"
HotKey	"WXK_F12"	Adjust Extended		"Shift+F12"			"DisplayFrameGallery"
HotKey	"WXK_F9"	Adjust Constrain Extended		"Ctrl+Shift+F9"		"DisplayNameGallery"
HotKey	"WXK_UP"		Extended									  "CursorUp"					"NudgeUp1"
HotKey	"WXK_UP"		Extended	Constrain						  "Ctrl+CursorUp"				"NudgeUp5"
HotKey	"WXK_UP"		Extended	Adjust							  "Shift+CursorUp"				"NudgeUp10"
HotKey  "WXK_UP"		Extended	Constrain Adjust 				  "Ctrl+Shift+CursorUp"			"NudgeUpFifth"
HotKey	"WXK_UP"		Extended	Alternative						  "Alt+CursorUp"				"NudgeUpPixel1"
HotKey	"WXK_UP"		Extended	Alternative Adjust				  "Alt+Shift+CursorUp"			"NudgeUpPixel10"
HotKey	"WXK_DOWN"		Extended									  "CursorDown"					"NudgeDown1"
HotKey	"WXK_DOWN"		Extended	Constrain		   				  "Ctrl+CursorDown"			    "NudgeDown5"
HotKey	"WXK_DOWN"		Extended	Adjust			 				  "Shift+CursorDown"		    "NudgeDown10"
HotKey	"WXK_DOWN"		Extended	Constrain Adjust				  "Ctrl+Shift+CursorDown"		"NudgeDownFifth"
HotKey  "WXK_DOWN"		Extended	Alternative						  "Alt+CursorDown"				"NudgeDownPixel1"
HotKey	"WXK_DOWN"		Extended	Alternative Adjust				  "Alt+Shift+CursorDown"			"NudgeDownPixel10" 		
HotKey	"WXK_LEFT"		Extended									  "CursorLeft"					 "NudgeLeft1"
HotKey	"WXK_LEFT"		Extended	Constrain						  "Ctrl+CursorLeft"				 "NudgeLeft5"
HotKey	"WXK_LEFT"		Extended	Adjust							  "Shift+CursorLeft"			 "NudgeLeft10"
HotKey	"WXK_LEFT"		Extended	Constrain Adjust 				  "Ctrl+Shift+CursorLeft"		 "NudgeLeftFifth"
HotKey	"WXK_LEFT"		Extended	Alternative						  "Alt+CursorLeft"				 "NudgeLeftPixel1"
HotKey	"WXK_LEFT"		Extended	Alternative Adjust				  "Alt+Shift+CursorLeft"		 "NudgeLeftPixel10" 	
	
HotKey	"WXK_RIGHT"	Extended									  "CursorRight"					 "NudgeRight1"
HotKey	"WXK_RIGHT"	Extended	Constrain						  "Ctrl+CursorRight"			 "NudgeRight5"
HotKey	"WXK_RIGHT"	Extended	Adjust							  "Shift+CursorRight"			 "NudgeRight10"
HotKey	"WXK_RIGHT"	Extended	Constrain Adjust 				  "Ctrl+Shift+CursorRight"		 "NudgeRightFifth"
HotKey	"WXK_RIGHT"	Extended	Alternative						  "Alt+CursorRight"				 "NudgeRightPixel1"
HotKey  "WXK_RIGHT"	Extended	Alternative Adjust				  "Alt+Shift+CursorRight"		 "NudgeRightPixel10"
ToolSwitch	"WXK_X"	Alternative	"" "TOOL3"
ToolSwitch	"WXK_Z"	Alternative	"" "TOOL4"
ToolSwitch	"WXK_S"	Alternative	"" "TOOL7"
ToolSwitch	"WXK_SPACE"			"" "TOOL7"
HotKeyEnd
