HotKey	0x41		Constrain				"Ctrl+A"		"SelectAll"
HotKey	0x41		Adjust Constrain		"Ctrl+Shift+A"	"PasteAttributes"
HotKey	0x42		Constrain				"Ctrl+B"		"PutToBack"
HotKey	0x42		Adjust Constrain		"Ctrl+Shift+B"	"MoveBackwards"
HotKey	0x43		Constrain				"Ctrl+C"		"Copy"
HotKey	0x43 		Adjust Constrain 		"Ctrl+Shift+C"	"ConvertToBitmap"
HotKey	0x44		Constrain				"Ctrl+D"		"Duplicate"
HotKey	0x44		Adjust Constrain		"Ctrl+Shift+D"	"MoveBackwardsALayer"
HotKey	0x45		Constrain				"Ctrl+E"		"ColourPicker"
HotKey	0x45		Adjust Constrain		"Ctrl+Shift+E"	"Export"
HotKey	0x46		Constrain				"Ctrl+F"		"BringToFront"
HotKey	0x46		Adjust Constrain		"Ctrl+Shift+F"	"MoveForwards"
HotKey	0x47		Constrain				"Ctrl+G"		"Group"
HotKey	0x47		Adjust Constrain		"Ctrl+Shift+G"	"Group"
HotKey	0x57		Constrain				"Ctrl+W"		"URLImport"
HotKey	0x49		Adjust Constrain		"Ctrl+Shift+I"	"Import"
HotKey	0x49		Constrain				"Ctrl+I"		"ImageSlice"
HotKey	0x4A		Adjust Constrain		"Ctrl+Shift+J"	"ZoomDrawing"
HotKey	0x4B		Constrain				"Ctrl+K"		"EditClone"
HotKey	0x4C		Constrain				"Ctrl+L"		"ViewRulers"
HotKey	0x4C		Adjust Constrain		"Ctrl+Shift+L"	"ArrangeAlignment"
HotKey	0x4E		Constrain				"Ctrl+N"		"FileNewDrawing"
HotKey	0x4E		Adjust Constrain		"Ctrl+Shift+N"	"FileNewAnimation"
HotKey	0x4F		Constrain				"Ctrl+O"		"FileOpen"
HotKey	0x4F		Adjust Constrain		"Ctrl+Shift+O"	"UtilOptions"
HotKey	0x50		Constrain				"Ctrl+P"		"Print"
HotKey	0x50		Adjust Constrain		"Ctrl+Shift+P"	"ZoomSpread"
HotKey  0x52		Constrain				"Ctrl+R"		"ZoomPrev"
HotKey  0x52		Adjust Constrain		"Ctrl+Shift+R"	"ReverseStoryPath"
HotKey	0x53		Constrain				"Ctrl+S"		"FileSave"
HotKey	0x53		Adjust Constrain		"Ctrl+Shift+S"	"ConvertToShapes"
HotKey  0x54		Adjust Constrain		"Ctrl+Shift+T"	"TimeDraw"
HotKey	0x55		Constrain				"Ctrl+U"		"Ungroup"
HotKey	0x55		Adjust Constrain 		"Ctrl+Shift+U"	"MoveForwardsALayer"
HotKey	0x56		Constrain				"Ctrl+V"		"Paste"
HotKey	0x56		Adjust Constrain		"Ctrl+Shift+V"	"PasteAtSamePos"
HotKey	0x57		Adjust Constrain		"Ctrl+Shift+W"	"WebAddressDlg"
HotKey	0x58		Constrain				"Ctrl+X"		"Cut"
HotKey	0x59		Constrain				"Ctrl+Y"		"Redo"
HotKey	0x5A		Constrain				"Ctrl+Z"		"Undo"
HotKey  0x5A		Adjust Constrain		"Ctrl+Shift+Z"	"ZoomSelect"
HotKey	0xBC							"<"				"Undo"
HotKey	0xBE							">"				"Redo"
HotKey	0x1B							"Esc"			"SelectNone"
HotKey	0x08								"Backspace"		"Cut"
HotKey	0x7F 	Extended				"Del"			"Delete"
HotKey	0x7F 							"Del"			"Delete"
HotKey	0x2D 	Extended				"Ins"			"Paste"
HotKey	0xDE		CheckUnicode			"#"				"ShowGrid"
HotKey	0x0D							"Return"		"EditSelection"
HotKey	0x0D	Extended				"Enter"			"EditSelection"
HotKey	0x2D	Extended Adjust			"Shift+Insert"	"Paste"
HotKey	0x2D	Extended Constrain		"Ctrl+Insert"	"Copy"
HotKey	0x7F	Adjust					"Shift+Delete"	"Cut"
HotKey	0x7F	Extended Adjust			"Shift+Delete"	"Cut"
HotKey	0x13D							"NumPad 8"		"ViewFullScreen"
HotKey	0x70								"F1"			"HelpIndex"
HotKey	0x187	WorksInDrag				"NumPad *"		"SnapToObjects"
HotKey	0x185	WorksInDrag				"NumPad ."		"SnapToGrid"
HotKey	0x17D	WorksInDrag				"NumPad 2"		"SnapToGuides"
HotKey	0x182  						"NumPad 1"		"ShowGuides"
HotKey	0x31	Constrain			"Ctrl+1"			"AddShapes"
HotKey	0x32	Constrain			"Ctrl+2"			"SubtractShapes"
HotKey  0x33	Constrain			"Ctrl+3"			"IntersectShapes"
HotKey  0x34	Constrain			"Ctrl+4"			"SliceShapes"
HotKey  0x38	Adjust Constrain		"Ctrl+Shift+8"			"CXFTreeDlg"
HotKey  0x39	Adjust Constrain		"Ctrl+Shift+9"			"ThrottleCache"
HotKey  0x30	Adjust Constrain		"Ctrl+Shift+0"			"ClearCache"
HotKey  0x188	Constrain		"Ctrl+NumPad +"		"ZoomIn"
HotKey  0x18A	Constrain		"Ctrl+NumPad -"		"ZoomOut"
HotKey	0x31		Alternative		"Alt+1"				"TOOL13"
HotKey	0x32		Alternative		"Alt+2"				"TOOL17"
HotKey  0x33		Alternative		"Alt+3"				"TOOL22"
HotKey  0x34		Alternative		"Alt+4"				"TOOL23"
HotKey  0x35		Alternative		"Alt+5"				"TOOL24"
HotKey  0x36		Alternative		"Alt+6"				"TOOL16"
HotKey  0x37		Alternative		"Alt+7"				"TOOL19"
HotKey  0x38		Alternative		"Alt+8"				"TOOL25"
HotKey  0x39		Alternative		"Alt+9"				"TOOL3"
HotKey  0x30		Alternative		"Alt+0"				"TOOL4"
HotKey  0x157	Extended			"F2"				"TOOL7"
HotKey  0x158	Extended			"F3"				"TOOL6"
HotKey  0x159	Extended			"F4"				"TOOL11"
HotKey  0x15A	Extended			"F5"				"TOOL13"
HotKey	0x15B	Extended			"F6"				"TOOL17"
HotKey	0x15C	Extended			"F7"				"TOOL16"
HotKey	0x15D	Extended			"F8"				"TOOL21"
HotKey	0x157	Adjust Extended		"Shift+F2"			"TOOL18"
HotKey	0x158	Adjust Extended		"Shift+F3"			"TOOL5"
HotKey	0x159	Adjust Extended		"Shift+F4"			"TOOL12"
HotKey	0x15A	Adjust Extended		"Shift+F5"			"TOOL14"
HotKey	0x15B	Adjust Extended		"Shift+F6"			"TOOL19"
HotKey	0x15C	Adjust Extended		"Shift+F7"			"TOOL4"
HotKey	0x15D	Adjust Extended		"Shift+F8"			"TOOL3"
HotKey	0x157	Constrain Extended	"Ctrl+F2"			"TOOL22"
HotKey  0x158	Constrain Extended	"Ctrl+F3"			"TOOL23"
HotKey  0x15A	Constrain Extended	"Ctrl+F5"			"TOOL26"
HotKey	0x15C	Constrain Extended	"Ctrl+F7"			"TOOL24"
HotKey	0x15D	Constrain Extended	"Ctrl+F8"			"TOOL25"
HotKey	0x15E	Extended			"F9"				"DisplayColourGallery"
HotKey	0x15F	Extended			"F10"				"DisplayLayerGallery"
HotKey	0x160	Extended			"F11"				"DisplayBitmapGallery"
HotKey	0x161	Extended			"F12"				"DisplayLineGallery"
HotKey	0x15E	Adjust Extended		"Shift+F9"			"DisplayFontsGallery"
HotKey	0x15F	Adjust Extended		"Shift+F10"			"DisplayClipartGallery"
HotKey	0x160	Adjust Extended		"Shift+F11"			"DisplayFillsGallery"
HotKey	0x161	Adjust Extended		"Shift+F12"			"DisplayFrameGallery"
HotKey	0x15e	Adjust Constrain Extended		"Ctrl+Shift+F9"		"DisplayNameGallery"
HotKey	0x13d		Extended									  "CursorUp"					"NudgeUp1"
HotKey	0x13d		Extended	Constrain						  "Ctrl+CursorUp"				"NudgeUp5"
HotKey	0x13d		Extended	Adjust							  "Shift+CursorUp"				"NudgeUp10"
HotKey  0x13d		Extended	Constrain Adjust 				  "Ctrl+Shift+CursorUp"			"NudgeUpFifth"
HotKey	0x13d		Extended	Alternative						  "Alt+CursorUp"				"NudgeUpPixel1"
HotKey	0x13d		Extended	Alternative Adjust				  "Alt+Shift+CursorUp"			"NudgeUpPixel10"
HotKey	0x13f		Extended									  "CursorDown"					"NudgeDown1"
HotKey	0x13f		Extended	Constrain		   				  "Ctrl+CursorDown"			    "NudgeDown5"
HotKey	0x13f		Extended	Adjust			 				  "Shift+CursorDown"		    "NudgeDown10"
HotKey	0x13f		Extended	Constrain Adjust				  "Ctrl+Shift+CursorDown"		"NudgeDownFifth"
HotKey  0x13f		Extended	Alternative						  "Alt+CursorDown"				"NudgeDownPixel1"
HotKey	0x13f		Extended	Alternative Adjust				  "Alt+Shift+CursorUp"			"NudgeDownPixel10" 		
HotKey	0x13c		Extended									  "CursorLeft"					 "NudgeLeft1"
HotKey	0x13c		Extended	Constrain						  "Ctrl+CursorLeft"				 "NudgeLeft5"
HotKey	0x13c		Extended	Adjust							  "Shift+CursorLeft"			 "NudgeLeft10"
HotKey	0x13c		Extended	Constrain Adjust 				  "Ctrl+Shift+CursorLeft"		 "NudgeLeftFifth"
HotKey	0x13c		Extended	Alternative						  "Alt+CursorLeft"				 "NudgeLeftPixel1"
HotKey	0x13c		Extended	Alternative Adjust				  "Alt+Shift+CursorLeft"		 "NudgeLeftPixel10" 	
	
HotKey	0x13e	Extended									  "CursorRight"					 "NudgeRight1"
HotKey	0x13e	Extended	Constrain						  "Ctrl+CursorRight"			 "NudgeRight5"
HotKey	0x13e	Extended	Adjust							  "Shift+CursorRight"			 "NudgeRight10"
HotKey	0x13e	Extended	Constrain Adjust 				  "Ctrl+Shift+CursorRight"		 "NudgeRightFifth"
HotKey	0x13e	Extended	Alternative						  "Alt+CursorRight"				 "NudgeRightPixel1"
HotKey  0x13e	Extended	Alternative Adjust				  "Alt+Shift+CursorRight"		 "NudgeRightPixel10"
ToolSwitch	0x58	Alternative	"" "TOOL3"
ToolSwitch	0x5A	Alternative	"" "TOOL4"
ToolSwitch	0x53	Alternative	"" "TOOL7"
ToolSwitch	0x20			"" "TOOL7"
HotKeyEnd
